---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - wait_for: host={{ inventory_hostname }} port=22 timeout=5
    - junos_get_config:
        host={{ inventory_hostname }}
        user=root
        passwd=Juniper
        dest='files/{{ inventory_hostname }}_config.txt'
